/**
 * Censors profanity/bad words from text
 * @param {string} text - Input text
 * @param {Object} options - Options
 * @param {string[]} options.customWords - Additional words to censor
 * @param {string} options.replacement - Replacement character/string (default '*')
 * @returns {string} Censored text
 */
export default function censor(text, { customWords = [], replacement = '*' } = {}) {
  const badWords = [
    // Core profanity
    'fuck', 'shit', 'bitch', 'ass', 'damn', 'hell', 'crap', 'piss', 'dick', 'cock',
    'pussy', 'slut', 'whore', 'bastard', 'cunt', 'twat', 'wanker', 'bollocks', 'bugger',
    'dildo', 'vagina', 'penis', 'boob', 'tits', 'nipple', 'clit', 'anal', 'blowjob',
    'handjob', 'cum', 'semen', 'orgasm', 'porn', 'sex', 'masturbate', 'boner', 'erection',
    // Variations and compounds
    'fucking', 'fucker', 'fucked', 'fuckup', 'motherfucker', 'motherfucking', 'bullshit',
    'bullshit', 'dipshit', 'shithead', 'shitface', 'shitload', 'bullcrap', 'horseshit',
    'jackass', 'dumbass', 'smartass', 'badass', 'kickass', 'hardass', 'lazyass',
    'asshole', 'asshat', 'asswipe', 'assmunch', 'assclown', 'asshole', 'asses',
    'bitchy', 'bitches', 'bitching', 'bitchass', 'bitchtits',
    'bastard', 'bastards', 'bastardy',
    'cunt', 'cunts', 'cunty', 'cuntface',
    'dick', 'dicks', 'dickhead', 'dickweed', 'dickwad', 'dickhole', 'dickless',
    'cock', 'cocks', 'cockhead', 'cockbite', 'cockblock', 'cockroach',
    'pussy', 'pussies', 'pussycat', 'pussyfoot',
    'slut', 'sluts', 'slutty', 'slutbag',
    'whore', 'whores', 'whoring', 'doorwhore',
    'damn', 'damned', 'goddamn', 'goddamned', 'goddammit', 'damnit',
    'hell', 'hells', 'hellish', 'what the hell', 'go to hell',
    'crap', 'crappy', 'crapped', 'crapper',
    'piss', 'pissed', 'pissing', 'pissant', 'pissoff', 'pisspot',
    'nigga', 'nigger', 'niggers', 'negro', 'negroes',
    'fag', 'faggot', 'faggots', 'faggy', 'fagot',
    'dyke', 'dykes', 'dike',
    'queer', 'queers', 'queerity',
    'tranny', 'trannies', 'shemale',
    'retard', 'retarded', 'retardo',
    'spastic', 'spaz', 'spazz',
    // Sexual terms
    'blowjob', 'blowjobs', 'handjob', 'handjobs', 'deepthroat',
    'fucked', 'fucking', 'fucks', 'screw', 'screwed', 'screwing',
    'bang', 'banged', 'banging', 'shag', 'shagged', 'shagging',
    'root', 'rooting', 'poke', 'poking',
    'hookup', 'hooking up', 'one night stand',
    'strip', 'stripper', 'strippers',
    'nude', 'naked', 'nakedness',
    'boobs', 'titties', 'titty', 'boobies', 'tatas', 'jugs', 'knockers',
    'rack', 'racks', 'bazookas', 'melons',
    'boners', 'wood', 'stiffy', 'hardon', 'hardon', 'boner',
    'dick', 'dong', 'wiener', 'weenie', 'peen', 'johnson', 'pecker', 'todger',
    'schlong', 'dong', 'wang', 'willy', 'dingaling', 'meat',
    'twat', 'twats', 'twatwaffle', 'twatlips',
    'muff', 'muffdiving', 'carpetmuncher', 'rugmuncher',
    'rimjob', 'rimming', 'anilingus',
    'fisting', 'fistfuck',
    'gangbang', 'gangbanged',
    'threesome', 'foursome', 'orgy',
    'bukkake', 'creampie', 'facial',
    'pornstar', 'pornographic', 'xxx',
    'camgirl', 'camwhore',
    // Bodily functions/insults
    'fart', 'farted', 'farting', 'farts', 'farty',
    'burp', 'burped', 'burping', 'burps',
    'snot', 'snots', 'snotnose',
    'spit', 'spitting', 'spat', 'spittle',
    'sweat', 'sweaty', 'sweating',
    'pee', 'peed', 'peeing', 'peehole',
    'poop', 'pooped', 'pooping', 'poops', 'poopy',
    'doo doo', 'doodoo', 'poo', 'poo poo', 'poo-poo', 'pooey',
    'turds', 'turd', 'dookie', 'dookies', 'dung',
    'diarrhea', 'constipation',
    // Drug-related
    'weed', 'pot', 'mary jane', 'marijuana', 'cannabis', 'hash', 'hashish',
    'coke', 'cocaine', 'crack', 'crackhead', 'crackpipe',
    'heroin', 'meth', 'methhead', 'methamphetamine', 'ice', 'crystal',
    'ecstasy', 'xanax', 'oxy', 'oxycontin',
    'acid', 'lsd', 'shrooms', 'mushrooms', 'mdma',
    'opioid', 'opiate', 'fentanyl',
    'dope', 'dopehead', 'doper',
    'junkie', 'junk', 'stoner', 'stoned', 'high',
    'tripping', 'trippy', 'trip',
    'snort', 'snorted', 'snorting',
    'inject', 'injection', 'needle',
    'dealer', 'pusher',
    // Insults
    'idiot', 'moron', 'imbecile', 'stupid', 'dumb', 'dumbass',
    'retard', 'retarded', 'retardo', 'slowpoke',
    'ugly', 'ugliness', 'fat', 'fatass', 'fatso', 'chubby',
    'ugly bitch', 'ugly fuck',
    'loser', 'lame', 'lameo', 'lameass',
    'nerd', 'nerdy', 'geek', 'dweeb', 'dork',
    'weirdo', 'freak', 'freaky', 'creep', 'creepy',
    'hater', 'haters', 'jealous', 'envy',
    'wannabe', 'poser', 'fake',
    'trash', 'garbage', 'rubbish',
    'scum', 'scumbag', 'scumsucker',
    'slime', 'slimeball', 'slimy',
    'snake', 'snakelike', 'backstabber',
    'traitor', 'rat', 'snitch',
    'liar', 'lying', 'deceit', 'deceitful',
    'cheat', 'cheater', 'cheating',
    'thief', 'steal', 'stole', 'rob', 'robber',
    'murder', 'killer', 'kill', 'assassin',
    'rape', 'rapist', 'molest', 'molester', 'pedophile',
    'abuse', 'abuser', 'abusive',
    'stalker', 'stalking', 'creep',
    'psycho', 'psychopath', 'sociopath',
    'maniac', 'manic', 'crazy', 'insane', 'mad', 'nuts', 'bonkers', 'deranged',
    'mental', 'lunatic', 'unhinged',
    'sick', 'sicko', 'sick fuck',
    'disgusting', 'disgust', 'revolting', 'repulsive',
    'nasty', 'gross', 'grody', 'icky',
    'vile', 'vileness', 'filthy', 'filth',
    'dirty', 'dirtbag', 'dirtball',
    // Racial/ethnic slurs (common ones)
    'chink', 'gook', 'slope', 'gypsy', 'kike', 'spic', 'wetback',
    'polack', 'towelhead', 'raghead', 'sandnigger', 'cameljockey',
    'honkey', 'cracker', 'whitey', 'honky',
    'porch monkey', 'porchmonkey',
    'jap', 'japs',
    // Religious profanity
    'jesus christ', 'jesus fuck', 'jesus fuckin', 'jesus h christ',
    'christ almighty', 'christ on a cracker',
    'omg', 'oh my god', 'oh my gosh',
    'blasphemy', 'blasphemous',
    'sacrilege', 'sacrilegious',
    // Sexual orientation/gender
    'homo', 'homos', 'homoerotic',
    'lesbo', 'lesbian', 'lez', 'lezzie',
    'fag', 'fags', 'faggy', 'faggot', 'faggots',
    'tranny', 'shemale', 'he-she',
    'bitch made', 'bitch-ass', 'punk-ass',
    // Misc
    'shithead', 'shitface', 'shitbag', 'shitheel', 'shitstain',
    'shitheel', 'shithole', 'shithouse',
    'piss off', 'piss off', 'pissed off',
    'shit eating grin', 'shiteating',
    'clusterfuck', 'cluster fucked',
    'mindfuck', 'brainfuck', 'fuckbrain',
    'fucktard', 'fuckwad', 'fucknut', 'fucknugget',
    'dumbfuck', 'dumbfucker', 'dipshit', 'dipstick',
    'cunt', 'cunts', 'cunty', 'cuntface', 'cunthole',
    'mother fucker', 'mothafucker', 'muthafucka',
    'motherfucker', 'motherfuckers', 'motherfucking',
    'brotherfucker', 'sisterfucker',
    'shitfuck', 'fuckshit', 'bullshit',
    'assfuck', 'fuckass', 'assfucker',
    'cockfuck', 'fuckcock',
    'fuckboy', 'fuckface', 'fuckhead', 'fuckwit',
    'fuckhole', 'fuckhole', 'fuckstick',
    'fuck up', 'fuckup', 'fucked up',
    'what the fuck', 'wtf', 'wtf',
    'the fuck', 'the fuck',
    'fuck all', 'fuck around', 'fuck off',
    'fuck you', 'fuck me', 'fuck him', 'fuck her', 'fuck us', 'fuck them',
    'who gives a fuck', 'give a fuck', 'dont give a fuck',
    'give a shit', 'dont give a shit',
    'give a damn', 'dont give a damn',
    'holy shit', 'holy fuck', 'holy hell',
    'what the hell', 'what the heck',
    'go fuck yourself', 'go to hell', 'go to shit',
    'eat shit', 'eat a dick', 'suck my dick',
    'suck it', 'suck my', 'kiss my', 'bite me',
    'fuck off', 'piss off', 'fuck you', 'fuck off',
    'drop dead', 'die', 'die bitch', 'die fucker',
    'go die', 'go kill yourself',
    'shut the fuck up', 'shut up', 'stfu',
    'shut your mouth', 'shut your pie hole',
    'shut your trap', 'shut it',
    'get fucked', 'get bent', 'go blow',
    'kiss my ass', 'kiss my arse', 'lick my balls',
    'up yours', 'bite my ass', 'eat my ass',
    'fuck a duck', 'fuck a sheep',
    'clusterfuck', 'mindfuck',
    // Internet/gaming slang profanity
    'noob', 'noobs', 'n00b', 'n00bs', 'newbie', 'newb',
    'camper', 'camper', 'tryhard', 'sweaty',
    'smurf', 'smurfing', 'smurf account',
    'toxic', 'toxicity',
    'rage', 'ragequit', 'rage quit',
    'scrub', 'scrubs',
    'bot', 'bots', 'bot player',
    'hacker', 'hacking', 'hax', 'cheater', 'cheat',
    'exploiter', 'exploit',
    'griefer', 'griefing', 'troll', 'trolling',
    'flamer', 'flame', 'flaming',
    'report', 'reported', 'ban', 'banned',
    'trash talk', 'trash talker',
    'toxic player', 'salty', 'salty af',
    'get rekt', 'rekt',
    'owned', 'pwned', 'pwn',
    'ez', 'ez game', 'ez clap',
    // Additional offensive
    'abomination', 'atrocious', 'awful', 'horrible', 'terrible',
    'wretched', 'pathetic', 'pathetic', 'pitiful',
    'worthless', 'good for nothing', 'useless',
    'hopeless', 'failure', 'fail',
    'loser', 'reject', 'rejects',
    'misfit', 'outcast', 'misfit',
    'creep', 'creeps', 'creepy',
    'freak', 'freaks', 'freakish',
    'weirdo', 'weirdos',
    'gross', 'gross out',
    'disgusting', 'disgusting', 'revolting',
    'nauseating', 'sickening',
    'abhorrent', 'despicable', 'detestable',
    'contemptible', 'loathsome', 'odious',
    // Body parts (mild)
    'butt', 'butthole', 'buttface', 'buttcrack',
    'bum', 'bumhole', 'bummer',
    'arse', 'arsehole', 'arsewipe',
    'bollock', 'bollocks', 'bollocked',
    'twat', 'twats', 'twatface',
    'minge', 'minging',
    'fanny', 'fanny pack',
    'knob', 'knobend', 'knobhead', 'knobjockey',
    'prick', 'pricks', 'prickhead',
    'dork', 'dorkface', 'dorkhead',
    'dweeb', 'dweebs',
    'nerd', 'nerds', 'nerdy',
    'geek', 'geeks', 'geeky',
    'dork', 'dorks',
    'loser', 'losers',
    'moron', 'morons', 'moronic',
    'imbecile', 'imbeciles',
    'idiot', 'idiots', 'idiotic',
    'stupid', 'stupidity',
    'dumb', 'dumbass', 'dumbasses',
    'dunce', 'dunces',
    'oaf', 'oafs',
    'clod', 'clods',
    'lump', 'lumps',
    'blockhead', 'bonehead', 'meathead',
    'airhead', 'birdbrain', 'scatterbrain',
    'scatterbrained', 'ditzy',
    // Drug slang continued
    'roach', 'roach clip',
    'bong', 'bong hit',
    'pipe', 'crack pipe',
    'blunt', 'blunts',
    'joint', 'joints',
    'spliff', 'spliffs',
    'bowl', 'bong water',
    'kief', 'hash oil', 'shatter', 'wax',
    'dabs', 'dabbing',
    'edibles', 'edible',
    // More curse variations
    'goddammit', 'goddamn', 'goddamned', 'goddamn it',
    'jesus wept', 'jesus christ', 'jc',
    'for fucks sake', 'ffs',
    'for crying out loud',
    'what in the hell', 'what in gods name',
    'by the power of greyskull',
    'sweet jesus', 'holy jesus',
    'bloody', 'bloody hell', 'bloody mary',
    'bugger', 'bugger off', 'bugger it',
    'bollocks', 'the bollocks', 'absolute bollocks',
    'rubbish', 'rubbish bin', 'tosh',
    'codswallop', 'balderdash', 'poppycock',
    'twaddle', 'malarkey', 'malarkey',
    'hooey', 'baloney', 'malarkey',
    'bunk', 'bunkum',
    'nonsense', 'nonsensical',
    'horseshit', 'horse shit', 'horse crap',
    'load of shit', 'pile of shit',
    'piece of shit', 'pos',
    'waste of space', 'waste of time',
    'pain in the ass', 'pain in the arse',
    'pain in the neck', 'pain in the butt',
    'nuisance', 'menace', 'terror',
    'troublemaker', 'trouble maker',
    'aggravation', 'annoyance', 'irritation',
    'exasperation', 'frustration',
    'vexation', 'chagrin',
    'mortification', 'humiliation',
    'embarrassment', 'shame',
    'disgrace', 'disgraceful',
    'scandal', 'scandalous',
    'outrage', 'outrageous',
    'shocking', 'shockingly',
    'appalling', 'appallingly',
    'dreadful', 'dreadfully',
    'atrocious', 'atrociously',
    'abominable', 'abominably',
    'execrable', 'execrably',
    'heinous', 'heinously',
    // More sexual terms
    'lusty', 'lustful', 'lust',
    'horny', 'horniness',
    'aroused', 'arousal',
    'turned on', 'turned off',
    'excited', 'excitement',
    'throbbing', 'pulsing',
    'wet', 'wetness',
    'hard', 'stiff', 'rock hard',
    'soft', 'limp',
    'sensitive', 'sensitive area',
    'private parts', 'private',
    'naughty', 'naughty bits',
    'cheeky', 'cheeky bits',
    'saucy', 'saucy minx',
    'flirt', 'flirting', 'flirtatious',
    'seducer', 'seducing', 'seduction',
    'tempt', 'temptress', 'tempter',
    'enticing', 'enticement',
    'alluring', 'allurement',
    'bewitching', 'bewitchment',
    'captivating', 'captivation',
    'charming', 'charmer',
    'enchanting', 'enchantress',
    'fascinating', 'fascination',
    'mesmerizing', 'mesmerism',
    'spellbinding', 'spellbound',
    'hypnotic', 'hypnotism',
    'intoxicating', 'intoxication',
    'overpowering', 'overwhelming',
    // Internet toxicity
    'doxx', 'doxxing', 'doxxed',
    'swat', 'swatting', 'swatted', 'swat team',
    'brigade', 'brigading',
    'dogpile', 'dogpiling',
    'cancel', 'cancelled', 'cancel culture',
    'callout', 'called out', 'callout post',
    'ratio', 'ratioed',
    'ratioed', 'downvoted',
    'reported', 'mass reported',
    'banned', 'permabanned', 'tempbanned',
    'shadowbanned', 'shadow ban',
    'muted', 'timed out',
    'blocked', 'unfollowed',
    'ghosted', 'left on read',
    'roasted', 'destroyed', 'clapped',
    'dunked on', 'ratioed', 'dragged',
    'called', 'exposed', 'receipts',
    'receipts', 'proof', 'evidence',
    'screenshot', 'screen cap', 'sc',
    'thread', 'threadboy', 'threadbait',
    'ratio bait', 'rage bait', 'troll bait',
    'fishing', 'bait fishing',
    'engagement farming', 'engagement bait',
    'clout chaser', 'clout chasing',
    'clout', 'famous', 'infamous',
    'notorious', 'legendary', 'mythical',
    // Gaming terms
    'gg', 'gg ez', 'gg wp',
    'wp', 'wp ez',
    'noob', 'n00b', 'noobtube',
    'sweat', 'sweaty', 'sweaty tryhard',
    'sweaty gamer', 'sweaty player',
    'sweaty tryhard', 'tryhard gamer',
    'tryhard', 'tryharding',
    'sweaty tryhard',
    'sweat lord', 'sweat king',
    'sweaty tryhard', 'sweaty sweaty',
    'sweat', 'sweating',
    'sweaty tryhard', 'tryhard sweat',
    'tryharding', 'tryhard mode',
    'sweaty tryhard', 'sweat gaming',
    'sweat lord', 'sweat king',
    // More body/insult
    'ugly', 'ugly mug', 'ugly face',
    'hideous', 'hideousness',
    'grotesque', 'grotesqueness',
    'monstrous', 'monstrosity',
    'repulsive', 'repulsiveness',
    'off-putting', 'unattractive',
    'unappealing', 'unsightly',
    'ill-favored', 'ill-looking',
    'homely', 'plain', 'ordinary',
    'common', 'run-of-the-mill',
    'mediocre', 'mediocrity',
    'average', 'subpar', 'substandard',
    'inferior', 'inferiority',
    'second-rate', 'third-rate',
    'low-grade', 'bottom-feeder',
    'bottom of the barrel',
    'lowest of the low',
    'scraping the barrel',
    'scraping the bottom',
    'desperate', 'desperation',
    'pathetic', 'pathetically',
    'pitiful', 'pitifully',
    'sad', 'sadly', 'saddest',
    'tragic', 'tragically',
    'comic', 'comical', 'laughable',
    'ridiculous', 'ridiculously',
    'absurd', 'absurdity',
    'preposterous', 'preposterously',
    'ludicrous', 'ludicrously',
    'outlandish', 'outrageous',
    'fantastic', 'fantastical',
    'far-fetched', 'implausible',
    'unbelievable', 'unimaginable',
    'inconceivable', 'unthinkable',
    // Additional common insults
    'scumbag', 'scumbags',
    'dirtbag', 'dirtbags',
    'dirtball', 'dirtballs',
    'trashbag', 'trashbags',
    'garbage human', 'garbage person',
    'waste of skin', 'waste of life',
    'waste of air', 'waste of oxygen',
    'waste of food', 'waste of water',
    'waste of everything',
    'not worth the air',
    'not worth the time',
    'not worth the effort',
    'not worth the energy',
    'not worth the paper',
    'not worth the ink',
    'not worth the electrons',
    'not worth the atoms',
    'not worth the molecules',
    'not worth the space',
    'not worth the bandwidth',
    // Common cursing phrases
    'damn it all', 'damn it all to hell',
    'go to hell', 'go to hell in a handbasket',
    'go to hell in a handcart',
    'go to hell and back',
    'go to hell and dont come back',
    'go to hell and stay there',
    'to hell with it', 'to hell with you',
    'to hell with this', 'to hell with that',
    'what a load of crap', 'what a pile of crap',
    'what a heap of crap', 'what a bunch of crap',
    'what a bunch of bullshit',
    'what a load of bullshit',
    'what a pile of bullshit',
    'what a heap of bullshit',
    'what a bunch of horseshit',
    'what a load of horseshit',
    'what a pile of horseshit',
    'what a heap of horseshit',
    'what a bunch of nonsense',
    'what a load of nonsense',
    'what a pile of nonsense',
    'what a heap of nonsense',
    // More common insults
    'dumb as a rock', 'dumb as a box of rocks',
    'dumb as a bag of hammers',
    'dumb as a post',
    'not the sharpest tool in the shed',
    'not the brightest bulb',
    'not the fastest horse',
    'not the sharpest knife',
    'not the full deck',
    'a few fries short of a happy meal',
    'a few sandwiches short of a picnic',
    'a few cards short of a full deck',
    'a few bricks short of a full load',
    'a few clowns short of a circus',
    'a few clowns short of a circus',
    'a few pickles short of a jar',
    'a few tacos short of a combo plate',
    'the wheel is spinning but the hamsters dead',
    'the lights are on but nobodys home',
    'the porch light is on but nobodys home',
    'the elevator doesnt go all the way to the top',
    'the elevator doesnt go all the way up',
    'a few fries short of happy meal',
    'a few screws loose',
    'a screw loose',
    'a few marbles short of a bag',
    'a few marbles short of a game',
    // Swear word modifiers
    'fucking', 'fucking great', 'fucking amazing',
    'fucking awesome', 'fucking brilliant',
    'fucking terrible', 'fucking horrible',
    'fucking awful', 'fucking disgusting',
    'fucking stupid', 'fucking ridiculous',
    'fucking insane', 'fucking crazy',
    'fucking hilarious', 'fucking funny',
    'fucking epic', 'fucking legendary',
    'fucking badass', 'fucking badass',
    'fucking incredible', 'fucking unbelievable',
    'fucking mindblowing', 'fucking spectacular',
    'fucking phenomenal', 'fucking outstanding',
    'fucking magnificent', 'fucking glorious',
    'fucking wonderful', 'fucking fantastic',
    'fucking extraordinary', 'fucking remarkable',
    'fucking astonishing', 'fucking astounding',
    'fucking astonishing', 'fucking astounding',
    'shit', 'shitty', 'shittiest',
    'crappy', 'crappiest',
    'lame', 'lamest',
    'pathetic', 'most pathetic',
    'sad', 'saddest',
    'worst', 'worst ever',
    'worst game', 'worst movie',
    'worst player', 'worst team',
    'worst performance', 'worst attempt',
    // Common phrases with profanity
    'what the fuck', 'what the fuck',
    'what in the fuck', 'what the actual fuck',
    'what the fuck is this', 'what the fuck is going on',
    'what the fuck are you doing',
    'what the fuck are you talking about',
    'what the fuck do you want',
    'what the fuck do you mean',
    'what the fuck do you think',
    'what the fuck do you know',
    'what the fuck do you care',
    'who the fuck', 'who the fuck are you',
    'who the fuck do you think you are',
    'who the fuck do you think youre talking to',
    'who the fuck cares', 'who the fuck asked',
    'why the fuck', 'why the fuck not',
    'why the fuck would you',
    'why the fuck would anyone',
    'why the fuck would you do that',
    'why the fuck are you',
    'why the fuck is this',
    'where the fuck', 'where the fuck are you',
    'where the fuck is it',
    'where the fuck did it go',
    'where the fuck did you',
    'when the fuck', 'when the fuck did this',
    'when the fuck did that',
    'when the fuck did you',
    'how the fuck', 'how the fuck did',
    'how the fuck did this',
    'how the fuck did you',
    'how the fuck did that',
    'how the fuck does',
    'how the fuck does this',
    'how the fuck does that',
    // More misc profanity
    'bloody', 'bloody hell', 'bloody mary',
    'bloody idiot', 'bloody fool',
    'bloody nuisance', 'bloody pain',
    'bloody disaster', 'bloody mess',
    'bloody nightmare', 'bloody wreck',
    'bloody catastrophe', 'bloody tragedy',
    'bloody shame', 'bloody waste',
    'bloody disgrace', 'bloody scandal',
    'bloody rubbish', 'bloody garbage',
    'bloody trash', 'bloody filth',
    'bloody dirt', 'bloody muck',
    'bloody grime', 'bloody slime',
    'bloody slime', 'bloody muck',
    // Common profane interjections
    'dammit', 'goddammit', 'goddamn it',
    'shit', 'oh shit', 'oh shit oh shit',
    'holy shit', 'holy crap', 'holy hell',
    'holy fuck', 'holy moly',
    'good grief', 'good heavens', 'good god',
    'good god almighty', 'good gracious',
    'dear god', 'dear lord', 'dear jesus',
    'sweet mother of god', 'sweet jesus',
    'sweet christmas', 'sweet mercy',
    'sweet baby jesus', 'sweet lord',
    'dear sweet jesus',
    // More sexual
    'horny', 'horny af',
    'aroused', 'turned on',
    'turned off', 'not in the mood',
    'frigid', 'frigid bitch',
    'impotent', 'impotence',
    'dysfunction', 'erectile dysfunction',
    'premature', 'premature ejaculation',
    'small', 'tiny', 'microscopic',
    'micro', 'mini', 'miniscule',
    'puny', 'puny dick',
    'small dick', 'tiny dick',
    'small penis', 'tiny penis',
    'compensation', 'compensating',
    'overcompensating', 'overcompensation',
    'insecurity', 'insecure',
    'inferiority complex',
    // Final batch
    'shut the fuck up', 'stfu', 'stfu already',
    'shut the hell up', 'shut your fucking mouth',
    'shut your damn mouth', 'shut your pie hole',
    'shut your trap', 'shut it',
    'stfu and drive', 'stfu and play',
    'stfu and sleep', 'stfu and eat',
    'stfu and go away',
    'shut the fuck up and listen',
    'shut the fuck up and learn',
    'shut the fuck up and watch',
    'shut the fuck up and observe',
    'shut the fuck up and think',
    'shut the fuck up and reflect',
    'shut the fuck up and contemplate',
    'shut the fuck up and meditate',
    'shut the fuck up and ponder',
    'shut the fuck up and ruminate',
    'shut the fuck up and brood',
    'shut the fuck up and mope',
    'shut the fuck up and sulk',
    'shut the fuck up and pout',
    'shut the fuck up and frown',
    'shut the fuck up and scowl',
    'shut the fuck up and glare',
    'shut the fuck up and stare',
    'shut the fuck up and gawk',
    'shut the fuck up and gape',
    'shut the fuck up and gawp',
    'shut the fuck up and ogggle',
    'shut the fuck up and leer',
    'shut the fuck up and sneer',
    'shut the fuck up and smirk',
    'shut the fuck up and smile',
    'shut the fuck up and grin',
    'shut the fuck up and laugh',
    'shut the fuck up and giggle',
    'shut the fuck up and chuckle',
    'shut the fuck up and snicker',
    'shut the fuck up and snigger',
    'shut the fuck up and titter',
    'shut the fuck up and cackle',
    'shut the fuck up and guffaw',
    'shut the fuck up and roar',
    'shut the fuck up and bellow',
    'shut the fuck up and howl',
    'shut the fuck up and wail',
    'shut the fuck up and cry',
    'shut the fuck up and weep',
    'shut the fuck up and sob',
    'shut the fuck up and bawl',
    'shut the fuck up and blubber',
    'shut the fuck up and whimper',
    'shut the fuck up and whine',
    'shut the fuck up and moan',
    'shut the fuck up and groan',
    'shut the fuck up and complain',
    'shut the fuck up and grumble',
    'shut the fuck up and gripe',
    'shut the fuck up and grip',
    'shut the fuck up and carp',
    'shut the fuck up and kvetch',
    'shut the fuck up and whinge',
    'shut the fuck up and bellyache',
    'shut the fuck up and beef',
    'shut the fuck up and kick up a fuss',
    'shut the fuck up and make a fuss',
    'shut the fuck up and throw a tantrum',
    'shut the fuck up and throw a fit',
    'shut the fuck up and throw a wobbly',
    'shut the fuck up and throw a hissy',
    'shut the fuck up and have a hissy fit',
    'shut the fuck up and lose your shit',
    'shut the fuck up and lose your mind',
    'shut the fuck up and lose your cool',
    'shut the fuck up and lose your rag',
    'shut the fuck up and lose your temper',
    'shut the fuck up and fly off the handle',
    'shut the fuck up and blow your top',
    'shut the fuck up and blow your stack',
    'shut the fuck up and blow a gasket',
    'shut the fuck up and blow a fuse',
    'shut the fuck up and hit the roof',
    'shut the fuck up and hit the ceiling',
    'shut the fuck up and go ballistic',
    'shut the fuck up and go nuclear',
    'shut the fuck up and go ape',
    'shut the fuck up and go crazy',
    'shut the fuck up and go insane',
    'shut the fuck up and go mad',
    'shut the fuck up and go bonkers',
    'shut the fuck up and go bananas',
    'shut the fuck up and go nuts',
    'shut the fuck up and go loco',
    'shut the fuck up and go off the deep end',
    'shut the fuck up and lose it',
    'shut the fuck up and flip out',
    'shut the fuck up and flip your lid',
    'shut the fuck up and flip your wig',
    'shut the fuck up and flip your cork',
    'shut the fuck up and flip your shit',
    'shut the fuck up and lose your shit',
    'shut the fuck up and lose your goddamn mind',
    'shut the fuck up and lose your fucking mind',
    'shut the fuck up and lose your damn mind',
    'shut the fuck up and lose your bloody mind',
    'shut the fuck up and lose your fucking mind',
    // More
    'cock', 'cocks', 'cocksucker',
    'suck', 'sucks', 'sucked',
    'dick', 'dicks', 'dickhead',
    'prick', 'pricks',
    'tool', 'tools',
    'jerk', 'jerks', 'jerkoff',
    'wanker', 'wankers',
    'tosser', 'tossers',
    'muppet', 'muppets',
    'plonker', 'plonkers',
    'git', 'gits',
    'numpty', 'numpties',
    'bellend', 'bellends',
    'minge', 'minging',
    'knob', 'knobs', 'knobend',
    'knobhead', 'knobheads',
    'twat', 'twats',
    'twatwaffle', 'twatwaffles',
    'minger', 'mingers',
    'skank', 'skanks',
    'slag', 'slags',
    'tart', 'tarts',
    'slapper', 'slappers',
    'tramp', 'tramps',
    'bint', 'bints',
    'cow', 'cows',
    'sow', 'sows',
    'pig', 'pigs',
    'swine', 'swines',
    'dog', 'dogs',
    'bitch', 'bitches',
    'mong', 'mongo',
    'munt', 'munter',
    'beef', 'beefcake',
    'hunk', 'hunks',
    'stud', 'studs',
    'player', 'players',
    'fuckboy', 'fuckboys',
    'player', 'playah',
    'fuckgirl', 'fuckgirls',
    'hoe', 'hoes',
    'stripper', 'strippers',
    'exotic dancer', 'exotic dancers',
    'lap dancer', 'lap dancers',
    'pole dancer', 'pole dancers',
    'escort', 'escorts',
    'call girl', 'call girls',
    'prostitute', 'prostitutes',
    'hooker', 'hookers',
    'whore', 'whores',
    'slut', 'sluts',
    'tart', 'tarts',
    'slag', 'slags',
    'tramp', 'tramps',
    'bimbo', 'bimbos',
    'airhead', 'airheads',
    'ditz', 'ditzes',
    'bimbot', 'bimbots',
    'valley girl', 'valley girls',
    'princess', 'princesses',
    'drama queen', 'drama queens',
    'queen', 'queens',
    'diva', 'divas',
    'primadonna', 'primadonnas',
    'attention seeker', 'attention seekers',
    'clown', 'clowns',
    'joker', 'jokers',
    'buffoon', 'buffoons',
    'fool', 'fools',
    'idiot', 'idiots',
    'moron', 'morons',
    'imbecile', 'imbeciles',
    'dunce', 'dunces',
    'numbskull', 'numbskulls',
    'blockhead', 'blockheads',
    'bonehead', 'boneheads',
    'meathead', 'meatheads',
    'thicko', 'thickos',
    'thick', 'thick as shit',
    'dense', 'denser', 'densest',
    'dim', 'dimmer', 'dimmest',
    'dimwit', 'dimwits',
    'dimbulb', 'dimbulbs',
    'slow', 'slower', 'slowest',
    'slowpoke', 'slowpokes',
    'slowcoach', 'slowcoaches',
    'slowcoach', 'slowcoaches',
    'snail', 'snails',
    'tortoise', 'tortoises',
    'turtle', 'turtles',
    'sloth', 'sloths',
    'slug', 'slugs',
    'snail', 'snails',
    'worm', 'worms',
    'maggot', 'maggots',
    'grub', 'grubs',
    'larva', 'larvae',
    'caterpillar', 'caterpillars',
    'bug', 'bugs',
    'insect', 'insects',
    'pest', 'pests',
    'parasite', 'parasites',
    'leech', 'leeches',
    'tick', 'ticks',
    'flea', 'fleas',
    'louse', 'lice',
    'nit', 'nits',
    'cootie', 'cooties',
    'germ', 'germs',
    'bacteria', 'bacterias',
    'virus', 'viruses',
    'plague', 'plagues',
    'disease', 'diseases',
    'infection', 'infections',
    'contagion', 'contagions',
    'sickness', 'sicknesses',
    'illness', 'illnesses',
    'malady', 'maladies',
    'affliction', 'afflictions',
    'ailment', 'ailments',
    'condition', 'conditions',
    'disorder', 'disorders',
    'syndrome', 'syndromes',
    'problem', 'problems',
    'issue', 'issues',
    'trouble', 'troubles',
    'difficulty', 'difficulties',
    'hardship', 'hardships',
    'struggle', 'struggles',
    'battle', 'battles',
    'fight', 'fights',
    'war', 'wars',
    'conflict', 'conflicts',
    'dispute', 'disputes',
    'argument', 'arguments',
    'quarrel', 'quarrels',
    'row', 'rows',
    'tiff', 'tiffs',
    'spat', 'spats',
    'squabble', 'squabbles',
    'wrangle', 'wrangles',
    'altercation', 'altercations',
    'confrontation', 'confrontations',
    'showdown', 'showdowns',
    'clash', 'clashes',
    'collision', 'collisions',
    'crash', 'crashes',
    'smash', 'smashes',
    'bang', 'bangs',
    'boom', 'booms',
    'explosion', 'explosions',
    'blast', 'blasts',
    'detonation', 'detonations',
    'eruption', 'eruptions',
    'outbreak', 'outbreaks',
    'outburst', 'outbursts',
    'flare-up', 'flare-ups',
    'flareup', 'flareups',
    'fit', 'fits',
    'attack', 'attacks',
    'seizure', 'seizures',
    'spasm', 'spasms',
    'convulsion', 'convulsions',
    'twitch', 'twitches',
    'jerk', 'jerks',
    'jump', 'jumps',
    'start', 'starts',
    'shock', 'shocks',
    'surprise', 'surprises',
    'amazement', 'amaze',
    'wonder', 'wonders',
    'marvel', 'marvels',
    'spectacle', 'spectacles',
    'sight', 'sights',
    'scene', 'scenes',
    'sight', 'sights',
    'view', 'views',
    'vision', 'visions',
    'apparition', 'apparitions',
    'phantom', 'phantoms',
    'ghost', 'ghosts',
    'spirit', 'spirits',
    'specter', 'specters',
    'wraith', 'wraiths',
    'shade', 'shades',
    'shadow', 'shadows',
    'silhouette', 'silhouettes',
    'outline', 'outlines',
    'contour', 'contours',
    'profile', 'profiles',
    'form', 'forms',
    'shape', 'shapes',
    'figure', 'figures',
    'build', 'builds',
    'frame', 'frames',
    'body', 'bodies',
    'physique', 'physiques',
    'constitution', 'constitutions',
    'structure', 'structures',
    'makeup', 'makeups',
    'composition', 'compositions',
    'organization', 'organizations',
    'arrangement', 'arrangements',
    'order', 'orders',
    'system', 'systems',
    'method', 'methods',
    'procedure', 'procedures',
    'process', 'processes',
    'routine', 'routines',
    'practice', 'practices',
    'custom', 'customs',
    'tradition', 'traditions',
    'convention', 'conventions',
    'norm', 'norms',
    'standard', 'standards',
    'rule', 'rules',
    'law', 'laws',
    'regulation', 'regulations',
    'statute', 'statutes',
    'ordinance', 'ordinances',
    'decree', 'decrees',
    'edict', 'edicts',
    'command', 'commands',
    'order', 'orders',
    'directive', 'directives',
    'instruction', 'instructions',
    'direction', 'directions',
    'guidance', 'guidances',
    'advice', 'advices',
    'counsel', 'counsels',
    'guidance', 'guidances',
    'wisdom', 'wisdoms',
    'knowledge', 'knowledges',
    'understanding', 'understandings',
    'comprehension', 'comprehensions',
    'grasp', 'grasps',
    'hold', 'holds',
    'grip', 'grips',
    'clutch', 'clutches',
    'clasp', 'clasps',
    'embrace', 'embraces',
    'hug', 'hugs',
    'squeeze', 'squeezes',
    'press', 'presses',
    'push', 'pushes',
    'shove', 'shoves',
    'thrust', 'thrusts',
    'drive', 'drives',
    'force', 'forces',
    'compel', 'compels',
    'coerce', 'coerces',
    'pressure', 'pressures',
    'pressurize', 'pressurizes',
    'bully', 'bullies',
    'intimidate', 'intimidates',
    'threaten', 'threatens',
    'menace', 'menaces',
    'terrorize', 'terrorizes',
    'frighten', 'frightens',
    'scare', 'scares',
    'alarm', 'alarms',
    'startle', 'startles',
    'shock', 'shocks',
    'stun', 'stuns',
    'daze', 'dazes',
    'bewilder', 'bewilders',
    'confuse', 'confuses',
    'puzzle', 'puzzles',
    'perplex', 'perplexes',
    'baffle', 'baffles',
    'mystify', 'mystifies',
    'confound', 'confounds',
    'flummox', 'flummoxes',
    'flabbergast', 'flabbergasts',
    'astonish', 'astonishes',
    'amaze', 'amazes',
    'astound', 'astounds',
    'surprise', 'surprises',
    'stagger', 'staggers',
    'stumble', 'stumbles',
    'trip', 'trips',
    'fall', 'falls',
    'tumble', 'tumbles',
    'topple', 'topples',
    'collapse', 'collapses',
    'crumble', 'crumbles',
    'disintegrate', 'disintegrates',
    'dissolve', 'dissolves',
    'melt', 'melts',
    'thaw', 'thaws',
    'defrost', 'defrosts',
    'unfreeze', 'unfreezes',
    'soften', 'softens',
    'weaken', 'weakens',
    'diminish', 'diminishes',
    'decrease', 'decreases',
    'reduce', 'reduces',
    'lessen', 'lessens',
    'lower', 'lowers',
    'drop', 'drops',
    'fall', 'falls',
    'plunge', 'plunges',
    'dive', 'dives',
    'sink', 'sinks',
    'submerge', 'submerges',
    'immerse', 'immerses',
    'drown', 'drowns',
    'suffocate', 'suffocates',
    'smother', 'smothers',
    'choke', 'chokes',
    'strangle', 'strangles',
    'throttle', 'throttles',
    'gag', 'gags',
    'retch', 'retches',
    'vomit', 'vomits',
    'puke', 'pukes',
    'barf', 'barfs',
    'spew', 'spews',
    'regurgitate', 'regurgitates',
    'disgorge', 'disgorges',
    'eject', 'ejects',
    'expel', 'expels',
    'force out', 'forces out',
    'kick out', 'kicks out',
    'throw out', 'throws out',
    'toss out', 'tosses out',
    'cast out', 'casts out',
    'drive out', 'drives out',
    'oust', 'ousts',
    'banish', 'banishes',
    'exile', 'exiles',
    'deport', 'deports',
    'extradite', 'extradites',
    'repatriate', 'repatriates',
    'send back', 'sends back',
    'return', 'returns',
    'give back', 'gives back',
    'restore', 'restores',
    'reinstate', 'reinstates',
    'reestablish', 'reestablishes',
    'renew', 'renews',
    'revive', 'revives',
    'resurrect', 'resurrects',
    'reanimate', 'reanimates',
    'revitalize', 'revitalizes',
    'rejuvenate', 'rejuvenates',
    'refresh', 'refreshes',
    'recharge', 'recharges',
    'regenerate', 'regenerates',
    'rebuild', 'rebuilds',
    'reconstruct', 'reconstructs',
    'remake', 'remakes',
    'redo', 'redoes',
    'redo', 'redoes',
    'rework', 'reworks',
    'revamp', 'revamps',
    'renovate', 'renovates',
    'refurbish', 'refurbishes',
    'recondition', 'reconditions',
    'repair', 'repairs',
    'fix', 'fixes',
    'mend', 'mends',
    'patch', 'patches',
    'darn', 'darns',
    'stitch', 'stitches',
    'sew', 'sews',
    'suture', 'sutures',
    'bandage', 'bandages',
    'dress', 'dresses',
    'bind', 'binds',
    'tie', 'ties',
    'knot', 'knots',
    'loop', 'loops',
    'coil', 'coils',
    'curl', 'curls',
    'twist', 'twists',
    'turn', 'turns',
    'spin', 'spins',
    'rotate', 'rotates',
    'revolve', 'revolves',
    'orbit', 'orbits',
    'circle', 'circles',
    'cycle', 'cycles',
    'spin', 'spins',
    'whirl', 'whirls',
    'twirl', 'twirls',
    'pirouette', 'pirouettes',
    'dance', 'dances',
    'hop', 'hops',
    'skip', 'skips',
    'jump', 'jumps',
    'leap', 'leaps',
    'bound', 'bounds',
    'spring', 'springs',
    'bounce', 'bounces',
    'rebound', 'rebounds',
    'recoil', 'recoils',
    'flinch', 'flinches',
    'wince', 'winces',
    'grimace', 'grimaces',
    'scowl', 'scowls',
    'frown', 'frowns',
    'glare', 'glares',
    'stare', 'stares',
    'gaze', 'gazes',
    'look', 'looks',
    'peek', 'peeks',
    'peep', 'peeps',
    'peer', 'peers',
    'gawk', 'gawks',
    'gape', 'gapes',
    'ogle', 'ogles',
    'leer', 'leers',
    'ogle', 'ogles',
    'eye', 'eyes',
    'regard', 'regards',
    'observe', 'observes',
    'watch', 'watches',
    'view', 'views',
    'see', 'sees',
    'spot', 'spots',
    'notice', 'notices',
    'detect', 'detects',
    'discover', 'discovers',
    'find', 'finds',
    'locate', 'locates',
    'identify', 'identifies',
    'recognize', 'recognizes',
    'distinguish', 'distinguishes',
    'discern', 'discerns',
    'perceive', 'perceives',
    'sense', 'senses',
    'feel', 'feels',
    'touch', 'touches',
    'contact', 'contacts',
    'reach', 'reaches',
    'grasp', 'grasps',
    'clutch', 'clutches',
    'grab', 'grabs',
    'snatch', 'snatches',
    'seize', 'seizes',
    'take', 'takes',
    'catch', 'catches',
    'capture', 'captures',
    'trap', 'traps',
    'snare', 'snares',
    'ensnare', 'ensnares',
    'entrap', 'entraps',
    'catch', 'catches',
    'capture', 'captures',
    'bag', 'bags',
    'net', 'nets',
    'land', 'lands',
    'secure', 'secures',
    'obtain', 'obtains',
    'acquire', 'acquires',
    'get', 'gets',
    'gain', 'gains',
    'earn', 'earns',
    'win', 'wins',
    'achieve', 'achieves',
    'accomplish', 'accomplishes',
    'attain', 'attains',
    'reach', 'reaches',
    'arrive', 'arrives',
    'come', 'comes',
    'approach', 'approaches',
    'near', 'nears',
    'advance', 'advances',
    'progress', 'progresses',
    'proceed', 'proceeds',
    'continue', 'continues',
    'go on', 'goes on',
    'carry on', 'carries on',
    'keep on', 'keeps on',
    'persist', 'persists',
    'persevere', 'perseveres',
    'endure', 'endures',
    'last', 'lasts',
    'survive', 'survives',
    'live', 'lives',
    'exist', 'exists',
    'be', 'is',
    'remain', 'remains',
    'stay', 'stays',
    'wait', 'waits',
    'linger', 'lingers',
    'loiter', 'loiters',
    'hang around', 'hangs around',
    'hang out', 'hangs out',
    'chill', 'chills',
    'relax', 'relaxes',
    'rest', 'rests',
    'repose', 'reposes',
    'sleep', 'sleeps',
    'slumber', 'slumbers',
    'doze', 'dozes',
    'snooze', 'snoozes',
    'nap', 'naps',
    'catnap', 'catnaps',
    'siesta', 'siestas',
    'drowse', 'drowses',
    'nod off', 'nods off',
    'drop off', 'drops off',
    'fall asleep', 'falls asleep',
    'drift off', 'drifts off',
    'pass out', 'passes out',
    'black out', 'blacks out',
    'faint', 'faints',
    'collapse', 'collapses',
    'conk out', 'conks out',
    'keel over', 'keels over',
    'drop dead', 'drops dead',
    'kick the bucket', 'kicks the bucket',
    'bite the dust', 'bites the dust',
    'buy the farm', 'buys the farm',
    'croak', 'croaks',
    'snuff it', 'snuffs it',
    'push up daisies', 'pushes up daisies',
    'six feet under',
    'dead as a doornail',
    'dead as a dodo',
    'deceased',
    'departed',
    'gone',
    'late',
    'passed',
    'passed away',
    'passed on',
    'expired',
    'perished',
    'succumbed',
    'lost',
    'no more',
    'with the angels',
    'in a better place',
    'resting in peace',
    'rip',
    'rest in peace',
    'rest in pieces',
    'six feet under',
    'pushing up daisies',
    'worm food',
    'dead meat',
    'done for',
    'finished',
    'kaput',
    'through',
    'washed up',
    'history',
    'a goner',
    'a dead duck',
    'a lame duck',
    'a sitting duck',
    'a lost cause',
    'a hopeless case',
    'a lost soul',
    'a poor soul',
    'a sad case',
    'a sorry sight',
    'a sorry state',
    'a sorry mess',
    'a sorry excuse',
    'a pathetic excuse',
    'a sorry specimen',
    'a sorry example',
    'a poor example',
    'a bad example',
    'a terrible example',
    'a dreadful example',
    'a horrible example',
    'a ghastly example',
    'a hideous example',
    'an appalling example',
    'an atrocious example',
    'an abysmal example',
    'a deplorable example',
    'a lamentable example',
    'a disgraceful example',
    'a scandalous example',
    'an outrageous example',
    'a shocking example',
    'a glaring example',
    'a flagrant example',
    'a blatant example',
    'a brazen example',
    'an audacious example',
    'a bold example',
    'a daring example',
    'a fearless example',
    'a courageous example',
    'a brave example',
    'a valiant example',
    'a heroic example',
    'a gallant example',
    'a noble example',
    'a high-minded example',
    'a principled example',
    'an upright example',
    'an honorable example',
    'a respectable example',
    'a decent example',
    'a proper example',
    'a fitting example',
    'a suitable example',
    'an appropriate example',
    'a relevant example',
    'a pertinent example',
    'an apposite example',
    'a germane example',
    'a material example',
    'a significant example',
    'an important example',
    'a major example',
    'a key example',
    'a prime example',
    'a classic example',
    'a textbook example',
    'a perfect example',
    'a model example',
    'an ideal example',
    'an exemplary example',
    'a shining example',
    'a shining light',
    'a beacon',
    'a guiding light',
    'a guiding star',
    'a lodestar',
    'a polestar',
    'a north star',
    'a compass',
    'a guide',
    'a leader',
    'a pioneer',
    'a trailblazer',
    'a pathfinder',
    'a groundbreaker',
    'a trendsetter',
    'a trendsetter',
    'a style setter',
    'a fashion setter',
    'a taste setter',
    'a standard setter',
    'a benchmark',
    'a yardstick',
    'a touchstone',
    'a measuring stick',
    'a measuring rod',
    'a standard',
    'a criterion',
    'a test',
    'a trial',
    'a proving ground',
    'a training ground',
    'a testing ground',
    'a battleground',
    'a battlefield',
    'a field of battle',
    'a theater of war',
    'a war zone',
    'a combat zone',
    'a danger zone',
    'a red zone',
    'a hot zone',
    'a no-go area',
    'a no-go zone',
    'a forbidden zone',
    'a restricted area',
    'a prohibited area',
    'a barred area',
    'a closed area',
    'a shut area',
    'a locked area',
    'a sealed area',
    'a secure area',
    'a safe area',
    'a protected area',
    'a guarded area',
    'a defended area',
    'a fortified area',
    'a stronghold',
    'a fortress',
    'a citadel',
    'a castle',
    'a palace',
    'a mansion',
    'a villa',
    'a residence',
    'a dwelling',
    'a home',
    'a house',
    'a building',
    'a structure',
    'a construction',
    'an edifice',
    'an erection',
    'a tower',
    'a spire',
    'a steeple',
    'a minaret',
    'a pagoda',
    'a shrine',
    'a temple',
    'a church',
    'a chapel',
    'a cathedral',
    'a basilica',
    'a mosque',
    'a synagogue',
    'a meeting house',
    'a place of worship',
    'a holy place',
    'a sacred place',
    'a holy site',
    'a sacred site',
    'a holy ground',
    'a sacred ground',
    'hallowed ground',
    'sacred soil',
    'holy soil',
    'consecrated ground',
    'blessed ground',
    'sanctified ground',
    'holy territory',
    'sacred territory',
    'consecrated territory',
    'blessed territory',
    'sanctified territory',
    'holy land',
    'sacred land',
    'consecrated land',
    'blessed land',
    'sanctified land',
    // Additional swears and variations
    'fuck', 'fucks', 'fucked', 'fucking', 'fucker', 'fuckers',
    'shit', 'shits', 'shitted', 'shitting', 'shitty',
    'bitch', 'bitches', 'bitched', 'bitching', 'bitchy',
    'ass', 'asses', 'assed', 'assing', 'assy',
    'damn', 'damns', 'damned', 'damning',
    'hell', 'hells',
    'crap', 'craps', 'crapped', 'crapping', 'crappy',
    'piss', 'pisses', 'pissed', 'pissing',
    'dick', 'dicks',
    'cock', 'cocks',
    'pussy', 'pussies',
    'slut', 'sluts', 'slutty',
    'whore', 'whores',
    'bastard', 'bastards',
    'cunt', 'cunts',
    'twat', 'twats',
    'wanker', 'wankers',
    'bollocks',
    'bugger', 'buggers', 'buggered', 'buggering',
    'dildo', 'dildos',
    'vagina', 'vaginas',
    'penis', 'penises',
    'boob', 'boobs',
    'tit', 'tits', 'titty', 'titties',
    'nipple', 'nipples',
    'clit', 'clits', 'clitoris', 'clitorises',
    'anal',
    'blowjob', 'blowjobs',
    'handjob', 'handjobs',
    'cum', 'cummed', 'cumming',
    'semen',
    'orgasm', 'orgasms',
    'porn', 'porno', 'pornos', 'pornography',
    'sex', 'sexes',
    'masturbate', 'masturbates', 'masturbated', 'masturbating', 'masturbation',
    'boner', 'boners',
    'erection', 'erections',
    'motherfucker', 'motherfuckers', 'motherfucking',
    'mother fucker', 'mother fucking',
    'bullshit', 'bullshitted', 'bullshitting',
    'dipshit',
    'shithead', 'shitheads',
    'shitface', 'shitfaces',
    'shitload',
    'horseshit',
    'jackass', 'jackasses',
    'dumbass', 'dumbasses',
    'smartass', 'smartasses',
    'badass', 'badasses',
    'kickass',
    'hardass', 'hardasses',
    'lazyass',
    'asshole', 'assholes',
    'asshat', 'asshats',
    'asswipe', 'asswipes',
    'assmunch', 'assmunches',
    'assclown', 'assclowns',
    'goddamn', 'goddamned', 'goddammit', 'goddamnit',
    'goddammit', 'goddamnit', 'goddamn it',
    'faggot', 'faggots',
    'fag', 'fags',
    'faggy',
    'fagot', 'fagots',
    'dyke', 'dykes',
    'dike', 'dikes',
    'queer', 'queers',
    'tranny', 'trannies',
    'shemale', 'shemales',
    'retard', 'retarded', 'retardo', 'retards',
    'spastic', 'spaz', 'spazz',
    'nigga', 'nigger', 'niggers',
    'negro', 'negroes',
    'chink', 'chinks',
    'gook', 'gooks',
    'slope', 'slopes',
    'gypsy', 'gypsies',
    'kike', 'kikes',
    'spic', 'spics',
    'wetback', 'wetbacks',
    'polack', 'polacks',
    'towelhead', 'towelheads',
    'raghead', 'ragheads',
    'sandnigger',
    'cameljockey',
    'honkey', 'honkies',
    'cracker', 'crackers',
    'whitey',
    'honky', 'honkies',
    'porch monkey',
    'porchmonkey',
    'jap', 'japs',
    'deepthroat',
    'rimjob', 'rimjobs',
    'rimming',
    'fisting',
    'fistfuck',
    'gangbang', 'gangbangs',
    'gangbanged',
    'threesome', 'threesomes',
    'foursome', 'foursomes',
    'orgy', 'orgies',
    'bukkake',
    'creampie', 'creampies',
    'facial', 'facials',
    'pornstar', 'pornstars',
    'pornographic',
    'xxx',
    'camgirl', 'camgirls',
    'camwhore', 'camwhores',
    'hooker', 'hookers',
    'prostitute', 'prostitutes',
    'escort', 'escorts',
    'call girl', 'call girls',
    'lap dancer', 'lap dancers',
    'pole dancer', 'pole dancers',
    'exotic dancer', 'exotic dancers',
    'stripper', 'strippers',
    'strip', 'strips', 'stripped', 'stripping',
    'nude', 'nudes',
    'naked',
    'boobs', 'boobies',
    'titties', 'titty',
    'knockers',
    'jugs', 'rack', 'racks',
    'bazookas',
    'melons',
    'boner', 'boners',
    'wood',
    'stiffy', 'stiffies',
    'hardon',
    'dick', 'dickhead', 'dickweed', 'dickwad', 'dickhole', 'dickless',
    'dong', 'dongs',
    'wiener', 'wiener',
    'weenie', 'weenies',
    'peen',
    'johnson', 'johnsons',
    'pecker', 'peckers',
    'todger', 'todgers',
    'schlong', 'schlongs',
    'wang', 'wangs',
    'willy', 'willies',
    'dingaling',
    'twat', 'twatwaffle', 'twatlips',
    'muff', 'muffdiving',
    'carpetmuncher',
    'rugmuncher',
    'gangbang',
    'swinger', 'swingers',
    'swinging',
    'open relationship',
    'polyamory',
    'polyamorous',
    'poly',
    'fag',
    'homo', 'homos',
    'lesbo', 'lesbos',
    'lez', 'lezzie', 'lezzies',
    'fairy', 'fairies',
    'pansy', 'pansies',
    'poofter', 'poofters',
    'nancy', 'nancy boy',
    'sissy', 'sissies',
    'effeminate',
    'sodomite', 'sodomites',
    'buggery',
    'bugger', 'buggered',
    'sodomy',
    'bestiality',
    'zoophilia',
    'necrophilia',
    'necrophiliac',
    'pedophile', 'pedophiles',
    'pedophilia',
    'child molester',
    'child rapist',
    'rapist', 'rapists',
    'raped', 'rape',
    'raping',
    'molest', 'molested', 'molesting', 'molestation',
    'molester', 'molesters',
    'abuse', 'abused', 'abusing', 'abuser', 'abusers',
    'abusive',
    'incest',
    'incestuous',
    'taboo',
    'pervert', 'perverts',
    'perverted',
    'deviant', 'deviants',
    'deviant',
    'freak', 'freaks',
    'weirdo', 'weirdos',
    'sicko', 'sickos',
    'psycho', 'psychos',
    'psychopath', 'psychopaths',
    'sociopath', 'sociopaths',
    'maniac', 'maniacs',
    'lunatic', 'lunatics',
    'nutcase', 'nutcases',
    'crackpot', 'crackpots',
    'whacko', 'whackos',
    'wacko', 'wackos',
    'nutter', 'nutters',
    'fruitcake', 'fruitcakes',
    'loony', 'loonies',
    'looney', 'looneys',
    'madman', 'madmen',
    'madwoman', 'madwomen',
    'cuckoo',
    'bonkers',
    'bats', 'bats in the belfry',
    'batty',
    'nuts',
    'nutty',
    'crackers',
    'off your rocker',
    'off their rocker',
    'out to lunch',
    'not all there',
    'a few sandwiches short of a picnic',
    'not playing with a full deck',
    'the lights are on but nobodys home',
    'nobody home',
    'empty headed',
    'empty head',
    'birdbrained',
    'bird brain',
    'scatterbrained',
    'air headed',
    'air head',
    'flaky',
    'flakey',
    'spacey',
    'space cadet',
    'out of it',
    'checked out',
    'zonked',
    'zonked out',
    'spaced out',
    'high as a kite',
    'stoned',
    'wasted',
    'hammered',
    'plastered',
    'pissed',
    'drunk',
    'shitfaced',
    'wasted',
    'blitzed',
    'smashed',
    'trashed',
    'tanked',
    'tanked up',
    'loaded',
    'juiced',
    'buzzed',
    'lit',
    'sloshed',
    'soaked',
    'soused',
    'pickled',
    'stewed',
    'fried',
    'bombed',
    'blasted',
    'blitzed',
    'cockeyed',
    'crooked',
    'bent',
    'curved',
    'twisted',
    'warped',
    'distorted',
    'deformed',
    'misshapen',
    'mangled',
    'mutilated',
    'maimed',
    'crippled',
    'lame',
    'hobbled',
    'limping',
    'gimp',
    'gimp leg',
    'gimp',
    'retard',
    'retarded',
    'slow',
    'dim',
    'dimwitted',
    'dimwitted',
    'thick',
    'dense',
    'stupid',
    'ignorant',
    'uneducated',
    'uninformed',
    'unaware',
    'clueless',
    'oblivious',
    'blind',
    'deaf',
    'dumb',
    'mute',
    'speechless',
    'tongue-tied',
    'at a loss for words',
    'wordless',
    'speechless',
    'voiceless',
    'silent',
    'quiet',
    'hushed',
    'muted',
    'subdued',
    'suppressed',
    'repressed',
    'oppressed',
    'subjugated',
    'enslaved',
    'enslaved',
    'captive',
    'imprisoned',
    'incarcerated',
    'jailed',
    'locked up',
    'behind bars',
    'in the slammer',
    'in the can',
    'in the clink',
    'in the pokey',
    'in the nick',
    'in the joint',
    'doing time',
    'serving time',
    'doing a stretch',
    'serving a stretch',
    'inside',
    'up the river',
    'away',
    'gone',
    'disappeared',
    'vanished',
    'missing',
    'absent',
    'away',
    'not here',
    'out',
    'out of town',
    'out of the office',
    'out of sight',
    'out of mind',
    'out of the picture',
    'out of the way',
    'out of the loop',
    'out of touch',
    'out of contact',
    'out of reach',
    'out of range',
    'out of bounds',
    'off limits',
    'forbidden',
    'prohibited',
    'banned',
    'barred',
    'excluded',
    'shut out',
    'locked out',
    'kept out',
    'not allowed',
    'not permitted',
    'not authorized',
    'not welcome',
    'unwanted',
    'undesired',
    'uninvited',
    'unwelcome guest',
    'unwelcome visitor',
    'intruder',
    'trespasser',
    'interloper',
    'gatecrasher',
    'party pooper',
    'killjoy',
    'wet blanket',
    'buzzkill',
    'downer',
    'drag',
    'bummer',
    'letdown',
    'disappointment',
    'disillusionment',
    'disenchantment',
    'discontent',
    'dissatisfaction',
    'displeasure',
    'disgust',
    'revulsion',
    'repugnance',
    'aversion',
    'antipathy',
    'hostility',
    'animosity',
    'enmity',
    'hatred',
    'hate',
    'loathing',
    'detestation',
    'abhorrence',
    'execration',
    'anathema',
    'curse',
    'damnation',
    'perdition',
    'hell',
    'hellfire',
    'inferno',
    'brimstone',
    'fire and brimstone',
    'torment',
    'torture',
    'agony',
    'anguish',
    'suffering',
    'pain',
    'hurt',
    'hurtful',
    'harmful',
    'damaging',
    'destructive',
    'devastating',
    'ruinous',
    'catastrophic',
    'disastrous',
    'calamitous',
    'tragic',
    'lamentable',
    'deplorable',
    'regrettable',
    'unfortunate',
    'unlucky',
    'ill-fated',
    'doomed',
    'cursed',
    'damned',
    'blighted',
    'plagued',
    'afflicted',
    'besieged',
    'troubled',
    'tormented',
    'tortured',
    'harassed',
    'harried',
    'hounded',
    'pestered',
    'badgered',
    'nagged',
    'nitpicked',
    'harped on',
    'droned on',
    'rambled on',
    'yammered on',
    'chattered on',
    'jabbered on',
    'babbled on',
    'blathered on',
    'gabbled on',
    'prattled on',
    'waffled on',
    'ranted on',
    'raved on',
    'stormed',
    'fumed',
    'seethed',
    'boiled',
    'simmered',
    'burned',
    'smoldered',
    'smouldered',
    'glowed',
    'blazed',
    'flamed',
    'flared',
    'exploded',
    'blew up',
    'detonated',
    'erupted',
    'burst',
    'popped',
    'snapped',
    'cracked',
    'split',
    'broke',
    'shattered',
    'smashed',
    'crashed',
    'collided',
    'banged',
    'bumped',
    'knocked',
    'hit',
    'struck',
    'punched',
    'slapped',
    'smacked',
    'whacked',
    'thwacked',
    'cuffed',
    'boxed',
    'battered',
    'beat',
    'thrashed',
    'walloped',
    'clobbered',
    'pounded',
    'pummeled',
    'pummeled',
    'buffeted',
    'battered',
    'mauled',
    'mangled',
    'torn',
    'ripped',
    'shredded',
    'tattered',
    'ragged',
    'battered',
    'bruised',
    'battered and bruised',
    'black and blue',
    'battered to a pulp',
    'beaten to a pulp',
    'beat to a pulp',
    'pounded to a pulp',
    'hammered to a pulp',
    'smashed to a pulp',
    'crushed',
    'squashed',
    'squeezed',
    'pressed',
    'squished',
    'mashed',
    'pureed',
    'blended',
    'mixed',
    'stirred',
    'shaken',
    'rattled',
    'jostled',
    'bumped',
    'jolted',
    'jolting',
    'jolts',
    'shocked',
    'jolted',
    'startled',
    'surprised',
    'amazed',
    'astonished',
    'astounded',
    'stunned',
    'dazed',
    'confused',
    'bewildered',
    'baffled',
    'mystified',
    'perplexed',
    'puzzled',
    'flummoxed',
    'flabbergasted',
    'dumbfounded',
    'dumbstruck',
    'dumbstruck',
    'speechless',
    'at a loss',
    'at a loss for words',
    'without words',
    'wordless',
    'voiceless',
    'tongue-tied',
    'frozen',
    'paralyzed',
    'petrified',
    'terrified',
    'frightened',
    'scared',
    'afraid',
    'fearful',
    'apprehensive',
    'anxious',
    'nervous',
    'jittery',
    'jumpy',
    'edgy',
    'uptight',
    'tense',
    'stressed',
    'stressed out',
    'under pressure',
    'harassed',
    'hounded',
    'pestered',
    'badgered',
    'nagged',
    'hassled',
    'bothered',
    'troubled',
    'worried',
    'concerned',
    'disturbed',
    'upset',
    'distressed',
    'anguished',
    'agonized',
    'tormented',
    'tortured',
    'plagued',
    'afflicted',
    'beset',
    'besieged',
    'harried',
    'harassed',
    'persecuted',
    'oppressed',
    'suppressed',
    'repressed',
    'subdued',
    'crushed',
    'quashed',
    'squashed',
    'squished',
    'stamped out',
    'stomped out',
    'trampled',
    'trampled on',
    'trodden on',
    'stepped on',
    'walked all over',
    'pushed around',
    'pushed over',
    'kicked around',
    'kicked down',
    'knocked down',
    'knocked over',
    'bowled over',
    'floored',
    'flattened',
    'leveled',
    'razed',
    'demolished',
    'destroyed',
    'annihilated',
    'obliterated',
    'wiped out',
    'eradicated',
    'exterminated',
    'extinguished',
    'quenched',
    'slaked',
    'satisfied',
    'appeased',
    'pacified',
    'mollified',
    'placated',
    'conciliated',
    'propitiated',
    'soothed',
    'calmed',
    'quieted',
    'hushed',
    'silenced',
    'muzzled',
    'gagged',
    'censored',
    'suppressed',
    'repressed',
    'stifled',
    'smothered',
    'choked',
    'strangled',
    'throttled',
    'suffocated',
    'asphyxiated',
    'smothered',
    'stifled',
    'repressed',
    'suppressed',
    'held back',
    'held in',
    'held down',
    'kept down',
    'kept in',
    'kept back',
    'restrained',
    'constrained',
    'confined',
    'restricted',
    'limited',
    'bounded',
    'fenced in',
    'walled in',
    'boxed in',
    'hemmed in',
    'penned in',
    'cooped up',
    'trapped',
    'caught',
    'snared',
    'ensnared',
    'entangled',
    'ensnarl',
    'enmesh',
    'immersed',
    'involved',
    'engaged',
    'occupied',
    'busy',
    'tied up',
    'bogged down',
    'mired',
    'stuck',
    'stuck in the mud',
    'bogged down',
    'mired down',
    'sunken',
    'submerged',
    'underwater',
    'drowned',
    'sunk',
    'lost',
    'gone',
    'departed',
    'left',
    'abandoned',
    'deserted',
    'forsaken',
    'forlorn',
    'lonely',
    'lonesome',
    'solitary',
    'alone',
    'by oneself',
    'on ones own',
    'single',
    'unattached',
    'unmarried',
    'unwed',
    'celibate',
    'chaste',
    'virtuous',
    'pure',
    'innocent',
    'naive',
    'ingenuous',
    'unsophisticated',
    'simple',
    'simple-minded',
    'simpleminded',
    'childlike',
    'childish',
    'immature',
    'juvenile',
    'infantile',
    'puerile',
    'adolescent',
    'teenage',
    'youthful',
    'young',
    'new',
    'fresh',
    'green',
    'raw',
    'untested',
    'untried',
    'inexperienced',
    'unseasoned',
    'unproved',
    'unproven',
    'undeveloped',
    'unformed',
    'unshaped',
    'unmolded',
    'uncarved',
    'unhewn',
    'unworked',
    'unwrought',
    'unrefined',
    'unprocessed',
    'unpolished',
    'unvarnished',
    'unglazed',
    'unpainted',
    'unstained',
    'uncolored',
    'undyed',
    'unbleached',
    'unwhitened',
    'unlightened',
    'undarkened',
    'unshaded',
    'unshadowed',
    'unclouded',
    'unobscured',
    'unhidden',
    'unconcealed',
    'uncovered',
    'unveiled',
    'unmasked',
    'unscreened',
    'unshielded',
    'unprotected',
    'undefended',
    'unguarded',
    'unwatched',
    'unobserved',
    'unnoticed',
    'unseen',
    'unperceived',
    'undetected',
    'undiscovered',
    'unfound',
    'unlocated',
    'unidentified',
    'unknown',
    'unrecognized',
    'unacknowledged',
    'unadmitted',
    'unconfessed',
    'undeclared',
    'unstated',
    'unexpressed',
    'unspoken',
    'unsaid',
    'unuttered',
    'unvoiced',
    'unarticulated',
    'unpronounced',
    'unmentioned',
    'unnoted',
    'unrecorded',
    'unregistered',
    'unlisted',
    'uncatalogued',
    'unfiled',
    'unstored',
    'unarchived',
    'unsaved',
    'unpreserved',
    'unconserved',
    'unmaintained',
    'unkept',
    'unheld',
    'unretained',
    'unremembered',
    'unrecalled',
    'unrecollected',
    'unreminded',
    'unprompted',
    'untriggered',
    'unactivated',
    'uninitiated',
    'unstarted',
    'unbegun',
    'uncommenced',
    'unlaunched',
    'unopened',
    'uninitiated',
    'uninaugurated',
    'unintroduced',
    'unpresented',
    'unoffered',
    'unproffered',
    'untendered',
    'unsubmitted',
    'unpresented',
    'ungiven',
    'undelivered',
    'unconveyed',
    'untransported',
    'untransferred',
    'untransmitted',
    'uncommunicated',
    'unimparted',
    'unshared',
    'undistributed',
    'unallocated',
    'unallotted',
    'unassigned',
    'unappointed',
    'undesignated',
    'unnominated',
    'unelected',
    'unchosen',
    'unselected',
    'unpicked',
    'unpreferred',
    'unfavored',
    'unpreferred',
    'unliked',
    'unloved',
    'unadored',
    'unworshipped',
    'unrevered',
    'unvenerated',
    'unrespected',
    'unesteemed',
    'unvalued',
    'unprized',
    'untreasured',
    'uncherished',
    'uncared for',
    'unnurtured',
    'unfostered',
    'unraised',
    'unbred',
    'unreared',
    'unparented',
    'unmothered',
    'unfathered',
    'unbegotten',
    'unfathered',
    'unsired',
    'unspawned',
    'unhatched',
    'unborn',
    'unconceived',
    'uncreated',
    'unmade',
    'unformed',
    'unfashioned',
    'unshaped',
    'unmolded',
    'unforged',
    'unfabricated',
    'unmanufactured',
    'unproduced',
    'unbuilt',
    'unconstructed',
    'unassembled',
    'unput together',
    'uncompiled',
    'uncollected',
    'ungathered',
    'unamassed',
    'unaccumulated',
    'unhoarded',
    'unstored',
    'unstocked',
    'unsupplied',
    'unprovided',
    'unfurnished',
    'unequipped',
    'unoutfitted',
    'unrigged',
    'unfitted',
    'unsuited',
    'unadapted',
    'unadjusted',
    'unaltered',
    'unchanged',
    'unmodified',
    'unvaried',
    'unvaried',
    'unvariegated',
    'unmulticolored',
    'monochromatic',
    'monotone',
    'monotonous',
    'unvaried',
    'uniform',
    'consistent',
    'constant',
    'steady',
    'stable',
    'fixed',
    'set',
    'established',
    'settled',
    'determined',
    'decided',
    'resolved',
    'concluded',
    'finished',
    'completed',
    'done',
    'ended',
    'terminated',
    'ceased',
    'stopped',
    'halted',
    'stayed',
    'checked',
    'arrested',
    'interrupted',
    'suspended',
    'paused',
    'interrupted',
    'disrupted',
    'disordered',
    'disarranged',
    'disorganized',
    'deranged',
    'unsettled',
    'disturbed',
    'upset',
    'perturbed',
    'disquieted',
    'discomposed',
    'disconcerted',
    'flustered',
    'rattled',
    'shaken',
    'stirred',
    'moved',
    'touched',
    'affected',
    'influenced',
    'swayed',
    'biased',
    'prejudiced',
    'predisposed',
    'inclined',
    'disposed',
    'minded',
    'willed',
    'determined',
    'resolved',
    'intending',
    'meaning',
    'planning',
    'proposing',
    'designing',
    'scheming',
    'plotting',
    'conniving',
    'conspiring',
    'colluding',
    'cooperating',
    'collaborating',
    'working together',
    'teaming up',
    'joining forces',
    'uniting',
    'combining',
    'merging',
    'blending',
    'mixing',
    'mingling',
    'intermingling',
    'intertwining',
    'interweaving',
    'interlacing',
    'interlocking',
    'interconnecting',
    'interrelating',
    'interacting',
    'communicating',
    'corresponding',
    'conversing',
    'talking',
    'speaking',
    'chatting',
    'gossiping',
    'yapping',
    'jabbering',
    'chattering',
    'prattling',
    'babbling',
    'blabbering',
    'blathering',
    'gabbling',
    'gibbering',
    'rambling',
    'wandering',
    'straying',
    'roaming',
    'roving',
    'rambling',
    'meandering',
    'drifting',
    'floating',
    'sailing',
    'gliding',
    'sliding',
    'slipping',
    'skidding',
    'coasting',
    'drifting',
    'floating',
    'hovering',
    'hanging',
    'suspended',
    'dangling',
    'swinging',
    'swaying',
    'rocking',
    'rolling',
    'tumbling',
    'turning',
    'spinning',
    'rotating',
    'revolving',
    'circling',
    'orbiting',
    'gyrating',
    'whirling',
    'twirling',
    'pirouetting',
    'dancing',
    'prancing',
    'capering',
    'cavorting',
    'gamboling',
    'frolicking',
    'playing',
    'sporting',
    'romping',
    'ramping',
    'stamping',
    'tramping',
    'trudging',
    'plodding',
    'slogging',
    'tramping',
    'stomping',
    'clomping',
    'clumping',
    'thumping',
    'banging',
    'pounding',
    'hammering',
    'battering',
    'beating',
    'pummeling',
    'thrashing',
    'whipping',
    'lashing',
    'flogging',
    'scourging',
    'birching',
    'caning',
    'cane',
    'stick',
    'rod',
    'switch',
    'strap',
    'belt',
    'leather',
    'whip',
    'lash',
    'scourge',
    'flail',
    'thong',
    'cord',
    'rope',
    'cable',
    'wire',
    'string',
    'thread',
    'line',
    'cord',
    'tie',
    'bind',
    'fasten',
    'secure',
    'attach',
    'affix',
    'join',
    'connect',
    'link',
    'couple',
    'unite',
    'combine',
    'merge',
    'blend',
    'mix',
    'mingle',
    'commingle',
    'intermingle',
    'intermix',
    'interblend',
    'interweave',
    'interlace',
    'interlock',
    'intertwine',
    'entwine',
    'entangle',
    'ensnare',
    'ensnarl',
    'enmesh',
    'envelop',
    'enwrap',
    'swathe',
    'swaddle',
    'wrap',
    'cover',
    'clothe',
    'dress',
    'attire',
    'garb',
    'array',
    'appareled',
    'clad',
    'robed',
    'gowned',
    'suited',
    'fitted',
    'equipped',
    'outfitted',
    'rigged',
    'supplied',
    'provided',
    'furnished',
    'stocked',
    'stored',
    'filled',
    'packed',
    'loaded',
    'stuffed',
    'crammed',
    'jammed',
    'squeezed',
    'pressed',
    'pushed',
    'shoved',
    'thrust',
    'forced',
    'driven',
    'compelled',
    'coerced',
    'constrained',
    'obliged',
    'obligated',
    'required',
    'needed',
    'demanded',
    'requested',
    'asked',
    'begged',
    'pleaded',
    'implored',
    'beseeched',
    'entreated',
    'petitioned',
    'solicited',
    'appealed',
    'prayed',
    'supplicated',
    'importuned',
    'urged',
    'exhorted',
    'admonished',
    'warned',
    'cautioned',
    'advised',
    'counseled',
    'guided',
    'directed',
    'instructed',
    'taught',
    'educated',
    'trained',
    'coached',
    'tutored',
    'schooled',
    'drilled',
    'exercised',
    'practiced',
    'rehearsed',
    'prepared',
    'readied',
    'fitted',
    'equipped',
    'armed',
    'provided',
    'supplied',
    'furnished',
    'outfitted',
    'rigged',
    'equipped',
    'prepared',
    'ready',
    'set',
    'poised',
    'braced',
    'steeling',
    'nerving',
    'fortifying',
    'strengthening',
    'reinforcing',
    'bolstering',
    'supporting',
    'upholding',
    'sustaining',
    'maintaining',
    'preserving',
    'conserving',
    'protecting',
    'defending',
    'guarding',
    'shielding',
    'screening',
    'sheltering',
    'harboring',
    'housing',
    'accommodating',
    'lodging',
    'boarding',
    'rooming',
    'quartering',
    'billetting',
    'encamping',
    'camping',
    'tented',
    'pavilioned',
    'canopied',
    'covered',
    'roofed',
    'ceiled',
    'floored',
    'walled',
    'fenced',
    'enclosed',
    'surrounded',
    'encircled',
    'encompassed',
    'enveloped',
    'wrapped',
    'swathed',
    'swaddled',
    'bundled',
    'packed',
    'wrapped up',
    'covered up',
    'hidden',
    'concealed',
    'covered',
    'veiled',
    'masked',
    'disguised',
    'camouflaged',
    'cloaked',
    'shrouded',
    'screened',
    'shielded',
    'protected',
    'defended',
    'guarded',
    'watched',
    'observed',
    'monitored',
    'surveilled',
    'spied on',
    'shadowed',
    'trailed',
    'followed',
    'pursued',
    'chased',
    'hunted',
    'tracked',
    'traced',
    'sought',
    'searched for',
    'looked for',
    'hunted for',
    'quested for',
    'yearned for',
    'longed for',
    'craved',
    'desired',
    'wanted',
    'wished for',
    'hoped for',
    'aspired to',
    'aimed at',
    'targeted',
    'directed at',
    'pointed at',
    'aimed at',
    'leveled at',
    'trained on',
    'focused on',
    'concentrated on',
    'centered on',
    'fixed on',
    'set on',
    'bent on',
    'determined on',
    'resolved on',
    'intent on',
    'intent upon',
    'set upon',
    'bent upon',
    'dead set on',
    'hell-bent on',
    'determined to',
    'resolved to',
    'intent to',
    'meaning to',
    'planning to',
    'proposing to',
    'intending to',
    'aiming to',
    'striving to',
    'struggling to',
    'trying to',
    'attempting to',
    'endeavoring to',
    'seeking to',
    'working to',
    'laboring to',
    'toiling to',
    'slaving to',
    'grinding to',
    'slogging to',
    'plugging to',
    'pushing to',
    'driving to',
    'forcing to',
    'compelling to',
    'urging to',
    'pressing to',
    'hurrying to',
    'rushing to',
    'speeding to',
    'racing to',
    'dashing to',
    'sprinting to',
    'running to',
    'jogging to',
    'trotting to',
    'walking to',
    'strolling to',
    'sauntering to',
    'ambling to',
    'meandering to',
    'wandering to',
    'roaming to',
    'rambling to',
    'straying to',
    'deviating to',
    'diverging to',
    'branching to',
    'forking to',
    'splitting to',
    'dividing to',
    'separating to',
    'parting to',
    'leaving to',
    'departing to',
    'going to',
    'heading to',
    'moving to',
    'shifting to',
    'transferring to',
    'relocating to',
    'migrating to',
    'immigrating to',
    'emigrating to',
    'traveling to',
    'journeying to',
    'voyaging to',
    'cruising to',
    'sailing to',
    'flying to',
    'soaring to',
    'gliding to',
    'floating to',
    'drifting to',
    'blowing to',
    'wafting to',
    'carrying to',
    'bearing to',
    'bringing to',
    'taking to',
    'fetching to',
    'getting to',
    'obtaining to',
    'acquiring to',
    'gaining to',
    'earning to',
    'winning to',
    'achieving to',
    'attaining to',
    'reaching to',
    'arriving to',
    'coming to',
    'approaching to',
    'nearing to',
    'advancing to',
    'progressing to',
    'proceeding to',
    'continuing to',
    'going on to',
    'carrying on to',
    'keeping on to',
    'persisting to',
    'persevering to',
    'enduring to',
    'lasting to',
    'surviving to',
    'living to',
    'existing to',
    'being to',
    'remaining to',
    'staying to',
    'waiting to',
    'lingering to',
    'loitering to',
    'hanging to',
    'holding to',
    'clinging to',
    'gripping to',
    'clutching to',
    'grasping to',
    'seizing to',
    'snatching to',
    'grabbing to',
    'catching to',
    'capturing to',
    'trapping to',
    'snaring to',
    'ensnaring to',
    'entangling to',
    'ensnaring to',
    'enmeshing to',
    'entwining to',
    'twining to',
    'weaving to',
    'interweaving to',
    'interlacing to',
    'interlocking to',
    'interconnecting to',
    'interrelating to',
    'interacting to',
    'communicating to',
    'corresponding to',
    'writing to',
    'penning to',
    'scribbling to',
    'jotting to',
    'noting to',
    'recording to',
    'documenting to',
    'chronicling to',
    'registering to',
    'logging to',
    'entering to',
    'inscribing to',
    'engraving to',
    'etching to',
    'carving to',
    'cutting to',
    'sculpting to',
    'sculpturing to',
    'modeling to',
    'molding to',
    'shaping to',
    'forming to',
    'fashioning to',
    'making to',
    'creating to',
    'producing to',
    'generating to',
    'yielding to',
    'providing to',
    'supplying to',
    'furnishing to',
    'giving to',
    'offering to',
    'presenting to',
    'delivering to',
    'handing to',
    'passing to',
    'transferring to',
    'conveying to',
    'transporting to',
    'carrying to',
    'bearing to',
    'bringing to',
    'taking to',
    'fetching to',
    'getting to',
    'obtaining to',
    'acquiring to',
    'gaining to',
    'earning to',
    'winning to',
    'achieving to',
    'accomplishing to',
    'completing to',
    'finishing to',
    'ending to',
    'terminating to',
    'concluding to',
    'closing to',
    'shutting to',
    'sealing to',
    'locking to',
    'fastening to',
    'securing to',
    'tying to',
    'binding to',
    'lashing to',
    'tethering to',
    'leashing to',
    'hobbling to',
    'fettering to',
    'shackling to',
    'chaining to',
    'manacling to',
    'handcuffing to',
    'pinioning to',
    'restraining to',
    'constraining to',
    'restricting to',
    'limiting to',
    'confining to',
    'imprisoning to',
    'incarcerating to',
    'jailing to',
    'detaining to',
    'holding to',
    'keeping to',
    'retaining to',
    'maintaining to',
    'preserving to',
    'conserving to',
    'saving to',
    'storing to',
    'stocking to',
    'hoarding to',
    'accumulating to',
    'amassing to',
    'collecting to',
    'gathering to',
    'assembling to',
    'congregating to',
    'convening to',
    'meeting to',
    'encountering to',
    'facing to',
    'confronting to',
    'opposing to',
    'resisting to',
    'withstanding to',
    'withstanding to',
    'enduring to',
    'tolerating to',
    'bearing to',
    'standing to',
    'abiding to',
    'suffering to',
    'undergoing to',
    'experiencing to',
    'feeling to',
    'sensing to',
    'perceiving to',
    'detecting to',
    'noticing to',
    'observing to',
    'seeing to',
    'viewing to',
    'looking to',
    'watching to',
    'monitoring to',
    'surveilling to',
    'inspecting to',
    'examining to',
    'scrutinizing to',
    'studying to',
    'analyzing to',
    'investigating to',
    'exploring to',
    'probing to',
    'searching to',
    'seeking to',
    'hunting to',
    'tracking to',
    'tracing to',
    'following to',
    'pursuing to',
    'chasing to',
    'running after to',
    'going after to',
    'going for to',
    'reaching for to',
    'stretching for to',
    'straining for to',
    'striving for to',
    'struggling for to',
    'fighting for to',
    'battling for to',
    'warring for to',
    'campaigning for to',
    'crusading for to',
    'agitating for to',
    'protesting for to',
    'demonstrating for to',
    'marching for to',
    'rallying for to',
    'assembling for to',
    'gathering for to',
    'congregating for to',
    'convening for to',
    'meeting for to',
    'concurring for to',
    'agreeing for to',
    'consenting for to',
    'assenting for to',
    'acceding for to',
    'complying for to',
    'conforming for to',
    'adhering for to',
    'sticking for to',
    'clinging for to',
    'holding for to',
    'maintaining for to',
    'upholding for to',
    'supporting for to',
    'backing for to',
    'endorsing for to',
    'approving for to',
    'sanctioning for to',
    'authorizing for to',
    'permitting for to',
    'allowing for to',
    'letting for to',
    'enabling for to',
    'empowering for to',
    'licensing for to',
    'commissioning for to',
    'mandating for to',
    'ordering for to',
    'directing for to',
    'commanding for to',
    'instructing for to',
    'telling for to',
    'informing for to',
    'advising for to',
    'warning for to',
    'cautioning for to',
    'alerting for to',
    'notifying for to',
    'notifying for to'
  ];

  const allWords = [...new Set([...badWords, ...customWords])];
  let result = text;

  allWords.forEach(word => {
    const escaped = word.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const regex = new RegExp(`\\b${escaped}\\b`, 'gi');
    result = result.replace(regex, replacement.repeat(Math.min(word.length, 10)));
  });

  return result;
}
